export const UserConstants = {
    AUTH_TOKEN_UPDATE: 'AUTH_TOKEN_UPDATE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    USER_FAIL_REGISTER: 'USER_FAIL_REGISTER',
    USER_SUCCESS_REGISTER: 'USER_SUCCESS_REGISTER',
};
